"""Alembic migration script template"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4f3e56946e'
down_revision = 'fe676d02756d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_rule', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('reminder_offset', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('last_reminded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminded_at')
    op.drop_column('tasks', 'reminder_offset')
    op.drop_column('tasks', 'recurrence_rule')
    # ### end Alembic commands ###
