"""Alembic migration script template"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4f3e56946e'
down_revision = 'fe676d02756d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
